var allCountries={"countryName":[
   { "country":"Afghanistan"},
   { "country":"Akrotiri"},
   { "country":"Albania"},
   { "country":"Algeria"},
   { "country":"American Samoa"},
   { "country":"Andorra"},
   { "country":"Angola"},
   { "country":"Anguilla"},
   { "country":"Antarctica"},
   { "country":"Antigua and Barbuda"},
   { "country":"Argentina"},
   { "country":"Armenia"},
   { "country":"Aruba"},
   { "country":"Ashmore and Cartier Islands"},
   { "country":"Australia"},
   { "country":"Austria"},
   { "country":"Azerbaijan"},
   { "country":"Bahamas, The"},
   { "country":"Bahrain"},
   { "country":"Bangladesh"},
   { "country":"Barbados"},
   { "country":"Bassas da India"},
   { "country":"Belarus"},
   { "country":"Belgium"},
   { "country":"Belize"},
   { "country":"Benin"},
   { "country":"Bermuda"},
   { "country":"Bhutan"},
   { "country":"Bolivia"},
   { "country":"Bosnia and Herzegovina"},
   { "country":"Botswana"},
   { "country":"Bouvet Island"},
   { "country":"Brazil"},
   { "country":"British Indian Ocean Territory"},
   { "country":"British Virgin Islands"},
   { "country":"Brunei"},
   { "country":"Bulgaria"},
   { "country":"Burkina Faso"},
   { "country":"Burma"},
   { "country":"Burundi"},
   { "country":"Cambodia"},
   { "country":"Cameroon"},
   { "country":"Canada"},
   { "country":"Cape Verde"},
   { "country":"Cayman Islands"},
   { "country":"Central African Republic"},
   { "country":"Chad"},
   { "country":"Chile"},
   { "country":"China"},
   { "country":"Christmas Island"},
   { "country":"Clipperton Island"},
   { "country":"Cocos (Keeling) Islands"},
   { "country":"Colombia"},
   { "country":"Comoros"},
   { "country":"Congo, Democratic Republic of the"},
   { "country":"Congo, Republic of the"},
   { "country":"Cook Islands"},
   { "country":"Coral Sea Islands"},
   { "country":"Costa Rica"},
   { "country":"Cote d'Ivoire"},
   { "country":"Croatia"},
   { "country":"Cuba"},
   { "country":"Cyprus"},
   { "country":"Czech Republic"},
   { "country":"Denmark"},
   { "country":"Dhekelia"},
   { "country":"Djibouti"},
   { "country":"Dominica"},
   { "country":"Dominican Republic"},
   { "country":"Ecuador"},
   { "country":"Egypt"},
   { "country":"El Salvador"},
    { "country":"Equatorial Guinea"},
    { "country":"Eritrea"},
    { "country":"Estonia"},
    { "country":"Ethiopia"},
    { "country":"Europa Island"},
    { "country":"Falkland Islands (Islas Malvinas)"},
    { "country":"Faroe Islands"},
    { "country":"Fiji"},
    { "country":"Finland"},
    { "country":"France"},
    { "country":"French Guiana"},
    { "country":"French Polynesia"},
    { "country":"French Southern and Antarctic Lands"},
    { "country":"Gabon"},
    { "country":"Gambia, The"},
    { "country":"Gaza Strip"},
    { "country":"Georgia"},
    { "country":"Germany"},
    { "country":"Ghana"},
    { "country":"Gibraltar"},
    { "country":"Glorioso Islands"},
    { "country":"Greece"},
    { "country":"Greenland"},
    { "country":"Grenada"},
    { "country":"Guadeloupe"},
    { "country":"Guam"},
    { "country":"Guatemala"},
    { "country":"Guernsey"},
    { "country":"Guinea"},
    { "country":"Guinea-Bissau"},
    { "country":"Guyana"},
    { "country":"Haiti"},
    { "country":"Heard Island and McDonald Islands"},
    { "country":"Holy See (Vatican City)"},
    { "country":"Honduras"},
    { "country":"Hong Kong"},
    { "country":"Hungary"},
    { "country":"Iceland"},
    { "country":"India"},
    { "country":"Indonesia"},
    { "country":"Iran"},
    { "country":"Iraq"},
    { "country":"Ireland"},
    { "country":"Isle of Man"},
    { "country":"Israel"},
    { "country":"Italy"},
    { "country":"Jamaica"},
    { "country":"Jan Mayen"},
    { "country":"Japan"},
    { "country":"Jersey"},
    { "country":"Jordan"},
    { "country":"Juan de Nova Island"},
    { "country":"Kazakhstan"},
    { "country":"Kenya"},
    { "country":"Kiribati"},
    { "country":"Kosovo"},
    { "country":"Korea, North"},
    { "country":"Korea, South"},
    { "country":"Kuwait"},
    { "country":"Kyrgyzstan"},
    { "country":"Laos"},
    { "country":"Latvia"},
    { "country":"Lebanon"},
    { "country":"Lesotho"},
    { "country":"Liberia"},
    { "country":"Libya"},
    { "country":"Liechtenstein"},
    { "country":"Lithuania"},
    { "country":"Luxembourg"},
    { "country":"Macau"},
    { "country":"North Macedonia"},
    { "country":"Madagascar"},
    { "country":"Malawi"},
    { "country":"Malaysia"},
    { "country":"Maldives"},
    { "country":"Mali"},
    { "country":"Malta"},
    { "country":"Marshall Islands"},
    { "country":"Martinique"},
    { "country":"Mauritania"},
    { "country":"Mauritius"},
    { "country":"Mayotte"},
    { "country":"Mexico"},
    { "country":"Micronesia, Federated States of"},
    { "country":"Moldova"},
    { "country":"Monaco"},
    { "country":"Mongolia"},
    { "country":"Montserrat"},
    { "country":"Morocco"},
    { "country":"Mozambique"},
    { "country":"Namibia"},
    { "country":"Nauru"},
    { "country":"Navassa Island"},
    { "country":"Nepal"},
    { "country":"Netherlands"},
    { "country":"Netherlands Antilles"},
    { "country":"New Caledonia"},
    { "country":"New Zealand"},
    { "country":"Nicaragua"},
    { "country":"Niger"},
    { "country":"Nigeria"},
    { "country":"Niue"},
    { "country":"Norfolk Island"},
    { "country":"Northern Mariana Islands"},
    { "country":"Norway"},
    { "country":"Oman"},
    { "country":"Pakistan"},
    { "country":"Palau"},
    { "country":"Panama"},
    { "country":"Papua New Guinea"},
    { "country":"Paracel Islands"},
    { "country":"Paraguay"},
    { "country":"Peru"},
    { "country":"Philippines"},
    { "country":"Pitcairn Islands"},
    { "country":"Poland"},
    { "country":"Portugal"},
    { "country":"Puerto Rico"},
    { "country":"Qatar"},
    { "country":"Reunion"},
    { "country":"Romania"},
    { "country":"Russia"},
    { "country":"Rwanda"},
    { "country":"Saint Helena"},
    { "country":"Saint Kitts and Nevis"},
    { "country":"Saint Lucia"},
    { "country":"Saint Pierre and Miquelon"},
    { "country":"Saint Vincent and the Grenadines"},
    { "country":"Samoa"},
    { "country":"San Marino"},
    { "country":"Sao Tome and Principe"},
    { "country":"Saudi Arabia"},
    { "country":"Senegal"},
    { "country":"Serbia "},
    { "country":"Montenegro"},
    { "country":"Seychelles"},
    { "country":"Sierra Leone"},
    { "country":"Singapore"},
    { "country":"Slovakia"},
    { "country":"Slovenia"},
    { "country":"Solomon Islands"},
    { "country":"Somalia"},
    { "country":"South Africa"},
    { "country":"South Georgia and the South Sandwich Islands"},
    { "country":"Spain"},
    { "country":"Spratly Islands"},
    { "country":"Sri Lanka"},
    { "country":"Sudan"},
    { "country":"Suriname"},
    { "country":"Svalbard"},
    { "country":"Swaziland"},
    { "country":"Sweden"},
    { "country":"Switzerland"},
    { "country":"Syria"},
    { "country":"Taiwan"},
    { "country":"Tajikistan"},
    { "country":"Tanzania"},
    { "country":"Thailand"},
    { "country":"Timor-Leste"},
    { "country":"Togo"},
    { "country":"Tokelau"},
    { "country":"Tonga"},
    { "country":"Trinidad and Tobago"},
    { "country":"Tromelin Island"},
    { "country":"Tunisia"},
    { "country":"Turkey"},
    { "country":"Turkmenistan"},
    { "country":"Turks and Caicos Islands"},
    { "country":"Tuvalu"},
    { "country":"Uganda"},
    { "country":"Ukraine"},
    { "country":"United Arab Emirates"},
    { "country":"United Kingdom"},
    { "country":"United States"},
    { "country":"Uruguay"},
    { "country":"Uzbekistan"},
    { "country":"Vanuatu"},
    { "country":"Venezuela"},
    { "country":"Vietnam"},
    { "country":" Virgin Islands"},
    { "country":"Wake Island"},
    { "country":" Wallis and Futuna"},
    { "country":"West Bank"},
    { "country":"Western Sahara"},
    { "country":"Yemen"},
    { "country":"Zambia"},
    { "country":"Zimbabwe"}

]}